service: crossing-gif
provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  iamRoleARN: arn:aws:iam::069571769196:role/intersections-dev-IamRoleLambda-1MAAQQH68Y4YK
  cfLogs: true
  vpc:
      securityGroupIds:
        - sg-86ee31fb
      subnetIds: 
        - subnet-06f9595d

package:
  exclude:
    - credentials.csv
    - fetch_test.py
    - test.py
    - pg8000-1.10.6.dist-info/**
    - Pillow-3.4.2.dist-info/**
    - six-1.10.0.dist-info/**
    - requests-2.11.1.dist-info/**
    - setup.sh
    - ubuntu-xenial-16.04-cloudimg-console
    - Vagrantfile
    - .vagrant/**
    - .git/**
    - .gitignore
    - .DS_Store

functions:
  gifFromIntersection:
    handler: handler.gifFromIntersection 
    timeout: 300
    events:
      - http:
          path: gif/get
          method: get
    memorySize: 1536
